# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{view_driver}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Macovsky"]
  s.date = %q{2009-12-07}
  s.description = %q{Helps dry up Rails-views using sublayouts and sections}
  s.email = %q{robotector@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/view_driver.rb",
     "lib/view_driver/action_controller_extensions.rb",
     "lib/view_driver/image_tag_extension.rb",
     "lib/view_driver/normalized_section_template.rb",
     "lib/view_driver/sections.rb",
     "lib/view_driver/sections_collection.rb",
     "lib/view_driver/view_helpers.rb",
     "spec/sections_collection_spec.rb",
     "spec/sections_spec.rb",
     "spec/spec_helper.rb",
     "spec/view_driver_action_controller_extensions_spec.rb",
     "spec/view_helpers_spec.rb"
  ]
  s.homepage = %q{http://github.com/macovsky/view_driver}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Helps dry up Rails-views using sublayouts and sections}
  s.test_files = [
    "spec/sections_collection_spec.rb",
     "spec/sections_spec.rb",
     "spec/spec_helper.rb",
     "spec/view_driver_action_controller_extensions_spec.rb",
     "spec/view_helpers_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

